name: Extract Version from PR Branch

on:
  push:
    branches:
      - f/pr-test

jobs:
  extract-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number for the current commit
        id: get_pr_number
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });
            if (pulls.length === 0) {
              core.setFailed("No PR found for the current commit.");
            } else {
              const prNumber = pulls[0].number;
              core.setOutput("pr_number", prNumber);
            }

      - name: Get PR details and extract branch name and body
        id: get_pr_details
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.get_pr_number.outputs.pr_number }},
            });
            const branchName = pr.head.ref;
            const prBody = pr.body || "No PR body provided.";
            core.setOutput("branch_name", branchName);
            core.setOutput("pr_body", prBody);

      - name: Extract version from branch name and PR body
        id: extract_versions
        run: |
          # Extract branch name and PR body from previous steps
          BRANCH_NAME="${{ steps.get_pr_details.outputs.branch_name }}"
          PR_BODY="${{ steps.get_pr_details.outputs.pr_body }}"

          echo "Branch name: $BRANCH_NAME"
          echo "PR body: $PR_BODY"

          # Extract version from branch name (vX.X.X)
          if [[ "$BRANCH_NAME" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            BRANCH_VERSION="${BASH_REMATCH[1]}"
          else
            BRANCH_VERSION="No version in branch name"
          fi

          # Extract version from PR body (vX.X.X)
          if [[ "$PR_BODY" =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            BODY_VERSION="${BASH_REMATCH[1]}"
          else
            BODY_VERSION="No version in PR body"
          fi

          echo "Extracted version from branch name: $BRANCH_VERSION"
          echo "Extracted version from PR body: $BODY_VERSION"

          # Set outputs for subsequent steps
          echo "::set-output name=branch_version::$BRANCH_VERSION"
          echo "::set-output name=body_version::$BODY_VERSION"

      - name: Show extracted versions
        run: |
          echo "Branch version: ${{ steps.extract_versions.outputs.branch_version }}"
          echo "Body version: ${{ steps.extract_versions.outputs.body_version }}"
