name: Extract Version from PR Branch

on:
  push:
    branches:
      - f/pr-test

jobs:
  extract-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number for the current commit
        id: get_pr_number
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.request(
              'GET /repos/{owner}/{repo}/commits/{commit_sha}/pulls',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              }
            );
            if (pulls.length === 0) {
              core.setFailed("No PR found for the current commit.");
            } else {
              core.setOutput("pr_number", pulls[0].number);
            }

      - name: Get PR details and extract branch name and body
        id: get_pr_details
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.get_pr_number.outputs.pr_number }}
            });
            core.setOutput("branch_name", pr.head.ref);
            core.setOutput("pr_body", pr.body || "No PR body provided.");

      - name: Save PR body to file
        run: |
          echo "${{ steps.get_pr_details.outputs.pr_body }}" > pr_body.md
          echo "PR body saved to pr_body.md."

      - name: Extract version from branch name and PR body
        id: extract_versions
        run: |
          # Extract branch name and PR body from previous steps
          BRANCH_NAME="${{ steps.get_pr_details.outputs.branch_name }}"
          PR_BODY=$(cat pr_body.md)

          echo "Branch name: $BRANCH_NAME"
          echo "PR body file content:"
          echo "$PR_BODY"

          # Extract version from branch name (vX.X.X)
          if [[ "$BRANCH_NAME" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            BRANCH_VERSION="${BASH_REMATCH[1]}"
          else
            BRANCH_VERSION="No version in branch name"
          fi

          # Extract version from PR body (vX.X.X)
          if [[ "$PR_BODY" =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            BODY_VERSION="${BASH_REMATCH[1]}"
          else
            BODY_VERSION="No version in PR body"
          fi

          echo "Extracted version from branch name: $BRANCH_VERSION"
          echo "Extracted version from PR body: $BODY_VERSION"

          # Set outputs for subsequent steps
          echo "::set-output name=branch_version::$BRANCH_VERSION"
          echo "::set-output name=body_version::$BODY_VERSION"

      - name: Show extracted versions
        run: |
          echo "Branch version: ${{ steps.extract_versions.outputs.branch_version }}"
          echo "Body version: ${{ steps.extract_versions.outputs.body_version }}"

      - name: Show PR body file content
        run: |
          echo "PR body content:"
          cat pr_body.md
